# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a34a39bc650442e9a29fe18fa8f28a63e2cd46195cfbaa0f2d918a3fae5f5186157d9c9961582c6b59bc095304fa576bc208eac5603223384bdaef67179fed

test:
  secret_key_base: db4446a3b1cfc7d397aca4b240edb57f1380505a43dbb29d4732c9752607599324a356dff93430a2461d6fa3d07fd0ab16d5b935d418c27244673414e43b33ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
